services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: interdiscount_frontend_vue_prod
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - NODE_ENV=production
    networks:
      - interdiscount_network
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.allownonrunning=true"
      - "traefik.http.routers.interdiscount-vue.rule=Host(`interdiscount-vue.swiftapp.ch`)"
      - "traefik.http.routers.interdiscount-vue.entrypoints=websecure"
      - "traefik.http.routers.interdiscount-vue.tls.certresolver=letsencrypt"
      - "traefik.http.routers.interdiscount-vue.middlewares=sablier-interdiscount@file"
      - "traefik.http.services.interdiscount-vue.loadbalancer.server.port=80"
      - "sablier.enable=true"
      - "sablier.group=interdiscount"
    deploy:
      resources:
        limits:
          memory: 64M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  interdiscount_network:
    external: true
  traefik:
    external: true
